services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - kafka
      - database
    ports:
      - "5000:5000"
    environment:
      KAFKA_BROKER: kafka:9092
      DATABASE_URL: postgres://app_user:password@database:5432/covid19

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: covid19
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - frontend
    ports:
      - "81:81"
